"""initial migration

Revision ID: a9c3cbf2a27e
Revises: 
Create Date: 2024-04-16 20:58:41.658992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9c3cbf2a27e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aluno_cursos',
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], name='fk_aluno_cursos_aluno_id'),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], name='fk_aluno_cursos_curso_id'),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('aluno_id', 'curso_id')
    )
    op.create_table('prova',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=True),
    sa.Column('data_agendada', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prova')
    op.drop_table('aluno_cursos')
    op.drop_table('curso')
    op.drop_table('aluno')
    # ### end Alembic commands ###
