"""adjust ref

Revision ID: ab057d953985
Revises: c728c6efd378
Create Date: 2024-04-18 20:47:02.299530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab057d953985'
down_revision = 'c728c6efd378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_aluno_cursos')
    with op.batch_alter_table('aluno_cursos', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_aluno_cursos_curso_id', 'curso', ['curso_id'], ['id'])
        batch_op.create_foreign_key('fk_aluno_cursos_aluno_id', 'aluno', ['aluno_id'], ['id'])

    with op.batch_alter_table('prova', schema=None) as batch_op:
        batch_op.drop_constraint('fk_prova_aluno', type_='foreignkey')
        batch_op.create_foreign_key('fk_prova_aluno_id', 'aluno', ['aluno_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prova', schema=None) as batch_op:
        batch_op.drop_constraint('fk_prova_aluno_id', type_='foreignkey')  # Removendo a FK nova pelo nome dado na upgrade
        batch_op.create_foreign_key('fk_prova_aluno', 'aluno', ['aluno_id'], ['id'], ondelete='CASCADE')  # Recriando a FK antiga com o nome original e parâmetros originais


    with op.batch_alter_table('aluno_cursos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_aluno_cursos_aluno_id', type_='foreignkey')
        batch_op.drop_constraint('fk_aluno_cursos_curso_id', type_='foreignkey')

    op.create_table('_alembic_tmp_aluno_cursos',
    sa.Column('aluno_id', sa.INTEGER(), nullable=False),
    sa.Column('curso_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], name='fk_aluno_cursos_aluno_id'),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], name='fk_aluno_cursos_curso_id'),
    sa.PrimaryKeyConstraint('aluno_id', 'curso_id')
    )

    
    # ### end Alembic commands ###
